import dotenv from 'dotenv';
dotenv.config();

import { createPool } from '../src/db/index.ts';
import { drizzle } from 'drizzle-orm/node-postgres';
import * as schema from '../src/db/schema.ts';

const IMAGES = {
  // Cars & Vehicles
  greenBuggy: '/src/assets/images/rc_green_buggy_1790447228493.jpg',
  orangeBasher: '/src/assets/images/rc_orange_basher_1790447327200.jpg',
  blueMonster: '/src/assets/images/rc_blue_monster_1790447245358.jpg',
  blackCarbonBuggy: '/src/assets/images/category_rc_cars_1790434413337.jpg',
  yellowSupercar: '/src/assets/images/rc_yellow_supercar_1790447258260.jpg',
  orangeCageBuggy: '/src/assets/images/hero_rc_car_cinematic_1790434394611.jpg',
  purpleDrift: '/src/assets/images/rc_purple_drift_1790447269661.jpg',
  tanCrawler: '/src/assets/images/rc_tan_crawler_1790447282681.jpg',
  redTrailTruck: '/src/assets/images/rc_red_trail_truck_1790447295740.jpg',
  greenMilitaryTruck: '/src/assets/images/rc_military_truck_1790447310759.jpg',
  tealCrawler: '/src/assets/images/category_rc_crawlers_1790434426807.jpg',
  panzerTank: '/src/assets/images/rc_panzer_tank_1790447345489.jpg',
  yellowExcavator: '/src/assets/images/category_construction_1790434453033.jpg',
  catamaranBoat: '/src/assets/images/rc_catamaran_boat_1790447359811.jpg',
  stealthBoat: '/src/assets/images/category_rc_boats_1790434439161.jpg',

  // Spare Parts - strictly individual photos
  brushlessCombo: '/src/assets/images/rc_brushless_combo_1790447723251.jpg',
  diffGears: '/src/assets/images/rc_diff_gears_1790447733756.jpg',
  metalServo: '/src/assets/images/rc_metal_servo_1790447744447.jpg',
  aluminumShocks: '/src/assets/images/rc_aluminum_shocks_1790447756632.jpg',
  cvdShafts: '/src/assets/images/rc_cvd_shafts_1790447768527.jpg',

  // Accessories - strictly individual photos
  lipoBattery: '/src/assets/images/rc_lipo_battery_1790447662511.jpg',
  dualCharger: '/src/assets/images/rc_dual_charger_1790447677394.jpg',
  hexToolset: '/src/assets/images/rc_hex_toolset_1790447691188.jpg',
  beadlockWheels: '/src/assets/images/rc_beadlock_wheels_1790447702663.jpg',
  scaleWinch: '/src/assets/images/rc_scale_winch_1790447714727.jpg',
};

async function seedUniqueProducts() {
  const pool = createPool();
  const db = drizzle(pool, { schema });

  console.log('Clearing old product inventory to enforce 100% unique items and images...');
  try {
    await pool.query('DELETE FROM order_items;');
  } catch (e) {}
  await pool.query('DELETE FROM products;');

  const categories = await db.select().from(schema.categories);
  const brands = await db.select().from(schema.brands);

  const getCatId = (slug: string) => categories.find((c) => c.slug === slug)?.id || categories[0].id;
  const getBrandId = (slug: string) => brands.find((b) => b.slug === slug)?.id || brands[0].id;

  const UNIQUE_PRODUCTS = [
    // 1. Rock Crawlers
    {
      slug: 'rgt-ex86120-desert-fox',
      name: 'RGT EX86120 Desert Fox Expedition 4WD Crawler',
      brandId: getBrandId('rgt'),
      categoryId: getCatId('crawlers'),
      description: 'Scale desert tan expedition crawler with portal axles, 2-speed transmission, locked differentials, full roof rack with recovery boards, and high-torque 550 brushed motor.',
      price: '28500.00',
      compareAtPrice: '32000.00',
      thumbnail: IMAGES.tanCrawler,
      images: [IMAGES.tanCrawler],
      scale: '1:10',
      terrain: 'Rock Crawler / Expedition',
      driveType: '4WD Portal Axle',
      batteryType: '2S - 3S LiPo',
      skillLevel: 'Intermediate',
      material: 'Steel C-Channel & Composite',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: true,
    },
    {
      slug: 'fms-chevrolet-k10-silverado',
      name: 'FMS 1:10 Chevrolet K10 Silverado Trail Edition',
      brandId: getBrandId('fms'),
      categoryId: getCatId('crawlers'),
      description: 'Officially licensed hardbody vintage pickup truck in candy apple red with chrome details, working LED lights, scale interior, and multi-link trailing arm suspension.',
      price: '34500.00',
      compareAtPrice: '38000.00',
      thumbnail: IMAGES.redTrailTruck,
      images: [IMAGES.redTrailTruck],
      scale: '1:10',
      terrain: 'Scale Trail / Rock Obstacles',
      driveType: '4WD Solid Axle',
      batteryType: '2S LiPo',
      skillLevel: 'Beginner',
      material: 'Hardbody ABS & Metal Gearbox',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: false,
    },
    {
      slug: 'mnrc-mn45-military-truck',
      name: 'MNRC MN45 Classic Tactical 4x4 Military Off-Roader',
      brandId: getBrandId('mnrc'),
      categoryId: getCatId('crawlers'),
      description: 'Rugged olive drab green military utility truck with authentic canvas rear canopy, proportional digital throttle and steering, working headlights, and leaf-sprung all-terrain axles.',
      price: '9800.00',
      compareAtPrice: '11500.00',
      thumbnail: IMAGES.greenMilitaryTruck,
      images: [IMAGES.greenMilitaryTruck],
      scale: '1:12',
      terrain: 'Forest Trail / Mud',
      driveType: '4WD Shaft Driven',
      batteryType: '7.4V Li-ion',
      skillLevel: 'Beginner',
      material: 'Reinforced Nylon & Metal Gears',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: true,
    },
    {
      slug: 'rgt-ex86100-cruiser-v2',
      name: 'RGT EX86100 Cruiser V2 Articulated Rock Crawler',
      brandId: getBrandId('rgt'),
      categoryId: getCatId('crawlers'),
      description: 'Cyan and teal competition-ready crawler featuring split transmission with reverse rotation front output to eliminate torque twist on vertical granite walls.',
      price: '24000.00',
      compareAtPrice: '27500.00',
      thumbnail: IMAGES.tealCrawler,
      images: [IMAGES.tealCrawler],
      scale: '1:10',
      terrain: 'Extreme Boulders',
      driveType: '4WD Anti-Torque',
      batteryType: '2S - 3S LiPo',
      skillLevel: 'Intermediate',
      material: 'CNC Aluminum Links & C-Hubs',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: false,
    },

    // 2. Bashers & High Speed
    {
      slug: 'mjx-hyper-go-16207-buggy',
      name: 'MJX Hyper Go 16207 4WD Brushless Racing Buggy',
      brandId: getBrandId('mjx'),
      categoryId: getCatId('bashers'),
      description: '70+ km/h capable pocket rocket in vibrant neon lime green livery with metal oil shocks, honeycomb chassis plate, metal spur gear, and wheelie bar.',
      price: '15000.00',
      compareAtPrice: '17500.00',
      thumbnail: IMAGES.greenBuggy,
      images: [IMAGES.greenBuggy],
      scale: '1:16',
      terrain: 'Off-Road Dirt & Turf',
      driveType: 'Brushless 4WD',
      batteryType: '2S / 3S LiPo Ready',
      skillLevel: 'Intermediate',
      material: 'Metal Gears & Oil Shocks',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: true,
    },
    {
      slug: 'suchiyu-16104-truggy-pro',
      name: 'Suchiyu 16104 Truggy Pro High-Speed Off-Roader',
      brandId: getBrandId('suchiyu'),
      categoryId: getCatId('bashers'),
      description: 'Fiery bright orange wide-stance stadium truggy engineered for giant skate park airs, grass blasting, and high-velocity drift slides with LED roof bar.',
      price: '13500.00',
      compareAtPrice: '15800.00',
      thumbnail: IMAGES.orangeBasher,
      images: [IMAGES.orangeBasher],
      scale: '1:16',
      terrain: 'Gravel & Short Grass',
      driveType: '4WD Shaft Driven',
      batteryType: '7.4V 1300mAh Li-ion',
      skillLevel: 'Beginner',
      material: 'Heavy-Duty Flexible Polycarbonate',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: true,
    },
    {
      slug: 'suchiyu-16106-monster-truck',
      name: 'Suchiyu 16106 High-Clearance Monster Truck',
      brandId: getBrandId('suchiyu'),
      categoryId: getCatId('bashers'),
      description: 'Metallic electric blue monster truck featuring massive chevron tread tires, long-travel twin shock absorbers, and sealed differentials for aggressive obstacle bashing.',
      price: '14200.00',
      compareAtPrice: '16900.00',
      thumbnail: IMAGES.blueMonster,
      images: [IMAGES.blueMonster],
      scale: '1:14',
      terrain: 'Rough Mud & Rocky Hills',
      driveType: '4WD Monster',
      batteryType: '7.4V 1500mAh',
      skillLevel: 'Beginner',
      material: 'High-Impact Nylon & Steel Dogbones',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: false,
    },
    {
      slug: 'rlaarlo-carbon-pro-buggy',
      name: 'Rlaarlo Carbon Pro Brushless Off-Road Racer',
      brandId: getBrandId('rlaarlo'),
      categoryId: getCatId('bashers'),
      description: 'Competition grade carbon fiber chassis plate with high-output 4-pole brushless motor, red anodized beadlock wheels, and steel spiral cut differential gears.',
      price: '42000.00',
      compareAtPrice: '48000.00',
      thumbnail: IMAGES.blackCarbonBuggy,
      images: [IMAGES.blackCarbonBuggy],
      scale: '1:10',
      terrain: 'Clay Tracks & High Speed',
      driveType: 'Full Carbon 4WD',
      batteryType: '3S - 4S LiPo',
      skillLevel: 'Advanced',
      material: 'Full 3K Carbon Fiber & 7075 Alloy',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: false,
    },
    {
      slug: 'suchiyu-16101-dune-hunter',
      name: 'Suchiyu 16101 Dune Hunter Open-Cage Desert Buggy',
      brandId: getBrandId('suchiyu'),
      categoryId: getCatId('bashers'),
      description: 'Scale tubular roll-cage desert buggy in matte black and orange with dual spare tire rack, detailed cockpit driver figurines, and long-travel front A-arms.',
      price: '12800.00',
      compareAtPrice: '14500.00',
      thumbnail: IMAGES.orangeCageBuggy,
      images: [IMAGES.orangeCageBuggy],
      scale: '1:16',
      terrain: 'Sand Dunes & Desert Trail',
      driveType: '4WD Buggy',
      batteryType: '7.4V LiPo',
      skillLevel: 'Beginner',
      material: 'Tubular Composite Cage',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: true,
    },

    // 3. On-Road & Drift
    {
      slug: 'rlaarlo-ak-917-speed-yellow',
      name: 'Rlaarlo AK-917 100MPH Carbon GT Supercar',
      brandId: getBrandId('rlaarlo'),
      categoryId: getCatId('on-road'),
      description: 'Aerodynamic supercar in brilliant racing yellow with carbon fiber side skirts, dual rear spoiler, high-speed foam belted slicks, and CNC aluminum motor mount.',
      price: '38500.00',
      compareAtPrice: '44000.00',
      thumbnail: IMAGES.yellowSupercar,
      images: [IMAGES.yellowSupercar],
      scale: '1:10',
      terrain: 'Smooth Asphalt & Runway',
      driveType: 'Belt / Shaft High-Speed',
      batteryType: '3S - 4S LiPo',
      skillLevel: 'Advanced',
      material: 'Carbon Fiber & CNC Alloy',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: true,
    },
    {
      slug: 'rlaarlo-am-d12-gyro-drift',
      name: 'Rlaarlo AM-D12 Gyro Electronic Drift Machine',
      brandId: getBrandId('rlaarlo'),
      categoryId: getCatId('drift'),
      description: 'Deep metallic pearl purple and white widebody drift machine equipped with integrated steer gyro, camber angle adjustments, and hard PE drift compounds for sideways control.',
      price: '22500.00',
      compareAtPrice: '26000.00',
      thumbnail: IMAGES.purpleDrift,
      images: [IMAGES.purpleDrift],
      scale: '1:10',
      terrain: 'Polished Concrete & Asphalt',
      driveType: 'RWD / AWD Drift Chassis',
      batteryType: '2S LiPo',
      skillLevel: 'Intermediate',
      material: 'Aluminum Suspension & Hard Compound',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: false,
    },

    // 4. Heavy Construction & Tanks
    {
      slug: 'heng-long-tiger-1-metal',
      name: 'Heng Long 1:16 Tiger I Heavy Armour Battle Tank',
      brandId: getBrandId('heng-long'),
      categoryId: getCatId('construction'),
      description: 'Camouflage battle tank featuring zinc alloy metal tracks, metal road wheels, full 360-degree turret rotation, realistic engine sound simulator, and recoil firing action.',
      price: '29500.00',
      compareAtPrice: '34000.00',
      thumbnail: IMAGES.panzerTank,
      images: [IMAGES.panzerTank],
      scale: '1:16',
      terrain: 'Rough Outdoor & Backyard',
      driveType: 'Twin Track Metal Gearbox',
      batteryType: '7.4V 1800mAh Li-ion',
      skillLevel: 'Intermediate',
      material: 'Die-cast Metal & High-Grade ABS',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: true,
    },
    {
      slug: 'heavy-excavator-all-metal',
      name: 'RC Heavy Duty Full-Metal Hydraulic Excavator',
      brandId: getBrandId('heng-long'),
      categoryId: getCatId('construction'),
      description: 'Authentic yellow heavy earth-moving excavator with working metal digging bucket, continuous boom articulation, individual track drive, and working cab searchlights.',
      price: '46000.00',
      compareAtPrice: '52000.00',
      thumbnail: IMAGES.yellowExcavator,
      images: [IMAGES.yellowExcavator],
      scale: '1:14',
      terrain: 'Dirt Works & Sand Excavation',
      driveType: 'Dual Track Hydraulic Simulation',
      batteryType: '7.4V 3000mAh',
      skillLevel: 'Intermediate',
      material: 'All-Alloy Bucket & Diecast Body',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: false,
    },

    // 5. Marine Boats
    {
      slug: 'rc-ocean-master-catamaran',
      name: 'RC Ocean Master Twin-Hull Brushless Speedboat',
      brandId: getBrandId('jjrc'),
      categoryId: getCatId('marine'),
      description: 'Cyan and white twin-hull racing catamaran with water-cooled 2848 brushless motor, CNC aluminum rudder, water-pickup system, and 65+ km/h top speed.',
      price: '19800.00',
      compareAtPrice: '23500.00',
      thumbnail: IMAGES.catamaranBoat,
      images: [IMAGES.catamaranBoat],
      scale: '650mm Hull',
      terrain: 'Lakes & Calm Open Water',
      driveType: 'Brushless Flex-Shaft Propeller',
      batteryType: '3S 11.1V LiPo',
      skillLevel: 'Intermediate',
      material: 'Hand-Laid Fiberglass & CNC Alloy',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: true,
    },
    {
      slug: 'rc-stealth-offshore-racer',
      name: 'RC Stealth Deep-V Offshore Racer',
      brandId: getBrandId('jiabaile'),
      categoryId: getCatId('marine'),
      description: 'Matte black hydrodynamic Deep-V wave-piercing speedboat with auto-righting rollover recovery system and dual magnetic water seals.',
      price: '14500.00',
      compareAtPrice: '17000.00',
      thumbnail: IMAGES.stealthBoat,
      images: [IMAGES.stealthBoat],
      scale: '500mm Hull',
      terrain: 'Ponds & Lakes',
      driveType: 'Water-Cooled Propeller',
      batteryType: '7.4V LiPo',
      skillLevel: 'Beginner',
      material: 'Impact-Resistant ABS Hull',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: false,
    },

    // 6. Spare Parts (100% Unique Image per Item!)
    {
      slug: 'brushless-motor-60a-esc-combo',
      name: 'Surpass Hobby 3650 Brushless Motor & 60A ESC Combo',
      brandId: getBrandId('mjx'),
      categoryId: getCatId('spare-parts'),
      description: '4-pole 12-slot sensorless high-torque brushless motor paired with an IP67 waterproof 60A brushless ESC with 6V/3A BEC output and active cooling fan.',
      price: '4850.00',
      compareAtPrice: '5800.00',
      thumbnail: IMAGES.brushlessCombo,
      images: [IMAGES.brushlessCombo],
      scale: '1:10 / 1:12',
      terrain: 'Universal Bashers & Drift',
      driveType: 'Electric Brushless Power System',
      batteryType: '2S - 3S LiPo',
      skillLevel: 'Intermediate',
      material: 'CNC Aluminum Ribbed Can & Silicon Wires',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: true,
    },
    {
      slug: 'hardened-steel-differential-gear-set',
      name: 'RGT Heavy Duty Hardened Steel Crown & Pinion Differential Gears',
      brandId: getBrandId('rgt'),
      categoryId: getCatId('spare-parts'),
      description: 'Precision spiral-cut heavy duty hardened carbon steel front and rear differential ring and pinion gear set. Eliminates stripped gears under high torque.',
      price: '1950.00',
      compareAtPrice: '2400.00',
      thumbnail: IMAGES.diffGears,
      images: [IMAGES.diffGears],
      scale: '1:10',
      terrain: 'Rock Crawler / Drivetrain',
      driveType: '4WD Ring & Pinion',
      batteryType: 'Universal',
      skillLevel: 'Advanced',
      material: 'Hardened #45 Carbon Steel',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: true,
    },
    {
      slug: 'waterproof-25kg-metal-gear-servo',
      name: 'Power HD 25KG High Torque Waterproof Digital Metal Gear Servo',
      brandId: getBrandId('rlaarlo'),
      categoryId: getCatId('spare-parts'),
      description: 'Lightning-fast 0.11s response time with 25kg/cm holding torque. IP67 waterproof anodized red CNC center aluminum case with steel gear train and dual ball bearings.',
      price: '2800.00',
      compareAtPrice: '3200.00',
      thumbnail: IMAGES.metalServo,
      images: [IMAGES.metalServo],
      scale: '1:8 / 1:10',
      terrain: 'All-Terrain Steering',
      driveType: 'Digital PWM Servo',
      batteryType: '6.0V - 7.4V HV',
      skillLevel: 'Intermediate',
      material: 'CNC Anodized Red Casing & Titanium Steel Gears',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: false,
    },
    {
      slug: 'cnc-aluminum-oil-filled-shocks',
      name: 'RGT 90mm CNC Anodized Blue Aluminum Oil-Filled Shocks (Pair)',
      brandId: getBrandId('rgt'),
      categoryId: getCatId('spare-parts'),
      description: 'Threaded body aluminum shocks with dual spring rates and precision silicone bladders for buttery smooth articulation over rocky obstacles.',
      price: '2450.00',
      compareAtPrice: '2900.00',
      thumbnail: IMAGES.aluminumShocks,
      images: [IMAGES.aluminumShocks],
      scale: '1:10',
      terrain: 'Rock Crawler & Trail',
      driveType: 'Suspension Dampers',
      batteryType: 'Universal',
      skillLevel: 'Beginner',
      material: 'T6-6061 Anodized Blue Billet Aluminum',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: true,
    },
    {
      slug: 'heavy-duty-cvd-drive-shafts',
      name: 'FMS Steel Heavy-Duty Front CVD Universal Joint Drive Shafts (Pair)',
      brandId: getBrandId('fms'),
      categoryId: getCatId('spare-parts'),
      description: 'Drop-in replacement constant velocity universal joint shafts engineered for extreme steering angles and heavy torque loads without binding or vibration.',
      price: '1650.00',
      compareAtPrice: '1990.00',
      thumbnail: IMAGES.cvdShafts,
      images: [IMAGES.cvdShafts],
      scale: '1:10 / 1:12',
      terrain: 'Crawler & Trail',
      driveType: 'Drivetrain Axles',
      batteryType: 'Universal',
      skillLevel: 'Intermediate',
      material: 'Tempered Spring Steel',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: false,
    },

    // 7. Accessories (100% Unique Image per Item!)
    {
      slug: '3s-5200mah-80c-lipo-battery',
      name: 'Gens Ace Bashing Series 3S 11.1V 5200mAh 80C Hardcase LiPo Battery',
      brandId: getBrandId('mjx'),
      categoryId: getCatId('accessories'),
      description: 'High-discharge 80C burst continuous LiPo pack equipped with heavy-gauge 10AWG silicone wiring and XT60 connector for maximum punch and prolonged runtimes.',
      price: '4600.00',
      compareAtPrice: '5200.00',
      thumbnail: IMAGES.lipoBattery,
      images: [IMAGES.lipoBattery],
      scale: 'Universal 1:8 / 1:10',
      terrain: 'Benchtop / Vehicle Tray',
      driveType: 'Power Pack',
      batteryType: '3S 11.1V 5200mAh 80C',
      skillLevel: 'Intermediate',
      material: 'Hardcase Flame-Retardant Polymer',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: true,
    },
    {
      slug: 'dual-smart-balance-charger-100w',
      name: 'ISDT D2 Mark II 200W Dual-Channel AC Smart Balance Charger',
      brandId: getBrandId('rlaarlo'),
      categoryId: getCatId('accessories'),
      description: 'Color LCD screen dual-port rapid balance charger with internal power supply. Charges LiPo, LiFe, LiHV, and NiMH packs simultaneously with active cooling.',
      price: '6800.00',
      compareAtPrice: '7999.00',
      thumbnail: IMAGES.dualCharger,
      images: [IMAGES.dualCharger],
      scale: 'Universal Pit Equipment',
      terrain: 'Workshop / Pit Station',
      driveType: 'Smart AC Charger',
      batteryType: '1S - 6S LiPo / LiHV',
      skillLevel: 'Beginner',
      material: 'Aluminum Heat Sink & Digital IPS Screen',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: false,
    },
    {
      slug: 'professional-7pc-titanium-hex-toolset',
      name: 'Dynamite RC Pro 7-Piece Titanium Nitride Hex & Nut Driver Tool Set',
      brandId: getBrandId('rgt'),
      categoryId: getCatId('accessories'),
      description: 'Machined ergonomic knurled aluminum handles with replaceable TiN titanium-coated precision tips (1.5mm, 2.0mm, 2.5mm, 3.0mm hex plus wheel nut sockets).',
      price: '3450.00',
      compareAtPrice: '4200.00',
      thumbnail: IMAGES.hexToolset,
      images: [IMAGES.hexToolset],
      scale: 'Universal Pit Tools',
      terrain: 'Workshop / Pit Mat',
      driveType: 'Precision Hand Tools',
      batteryType: 'N/A',
      skillLevel: 'Beginner',
      material: 'Titanium Nitride & Billet Knurled Aluminum',
      availability: 'IN_STOCK',
      featured: true,
      newArrival: true,
    },
    {
      slug: '1-10-beadlock-crawler-wheels-tires',
      name: 'Pro-Line Hyrax 1.9" Rock Terrain Tires on CNC Beadlock Wheels (4-Pack)',
      brandId: getBrandId('rgt'),
      categoryId: getCatId('accessories'),
      description: 'Super-soft sticky compound tires mounted on true 3-piece heavy brass-weighted aluminum beadlock rims for maximum grip on wet rock faces without gluing.',
      price: '5200.00',
      compareAtPrice: '6100.00',
      thumbnail: IMAGES.beadlockWheels,
      images: [IMAGES.beadlockWheels],
      scale: '1:10 Crawler',
      terrain: 'Wet Rock / Mud / Loose Sand',
      driveType: '4WD Wheel Set',
      batteryType: 'N/A',
      skillLevel: 'Beginner',
      material: 'Super Soft G8 Compound Rubber & CNC Bronze/Alloy',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: true,
    },
    {
      slug: 'wireless-dual-motor-metal-winch',
      name: 'RC4WD Scale 1:10 Heavy Duty Dual-Motor Metal Winch with Wireless Remote',
      brandId: getBrandId('fms'),
      categoryId: getCatId('accessories'),
      description: 'Cast metal body with functional synthetic braided line and spring steel tow hook. Operates via independent 2.4GHz keyfob wireless transmitter with 4.5kg pulling force.',
      price: '2750.00',
      compareAtPrice: '3300.00',
      thumbnail: IMAGES.scaleWinch,
      images: [IMAGES.scaleWinch],
      scale: '1:10 Crawler',
      terrain: 'Trail Recovery & Steep Climbing',
      driveType: 'Electric Winch',
      batteryType: '5V - 11V DC',
      skillLevel: 'Intermediate',
      material: 'Cast Zinc & Braided Synthetic Steel Rope',
      availability: 'IN_STOCK',
      featured: false,
      newArrival: false,
    },
  ];

  for (const item of UNIQUE_PRODUCTS) {
    await db.insert(schema.products).values(item);
    console.log(`Inserted: [${item.slug}] => ${item.thumbnail}`);
  }

  console.log(`Successfully seeded ${UNIQUE_PRODUCTS.length} strictly unique products with 100% unique photos!`);
  process.exit(0);
}

seedUniqueProducts().catch((err) => {
  console.error(err);
  process.exit(1);
});
